# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: make -C frotz/ dumb
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Get the Numbers
      run: echo "COVERAGE=$(npm run coverage | grep %)" >> $GITHUB_ENV
      
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.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 }}
        gistID: 554394d67973a35b66f7b60a24fa0950
        filename: frotzer-coverage.json
        label: Coverage
        message: ${{ env.COVERAGE }}
        color: blue
